### ISSUE TITLE
bug: displaying member list of another server in my server

### ISSUE THREAD

**Issue by TonehDev** [revoltchat/revolt#371] opened 2022-05-09 18:42 UTC
### What happened?

Whenever I go on another guy’s server and then my server, it displays the member list of the other guy’s server on my server.
![E4AD64BE-A2AC-40E6-ACD9-ADC7EACCBC23](https://user-images.githubusercontent.com/88310222/167476077-697aa987-7c93-4c24-8603-cd7001095861.png)

**Comment by Rexogamer** [comment] 2022-05-09 18:45
Duplicate of revoltchat/revite#593.

**Closed by Rexogamer** 2022-05-09 18:45 UTC
Labels: bug
