### ISSUE TITLE
Issue with creating accounts

### ISSUE THREAD

**Issue by WWEMGamer2** [revoltchat/revolt#362] opened 2022-05-05 07:05 UTC
Hello, I am Eric. 
There has been a specific issue with creating accounts on Revolt! My issue starts at when you have to verify your email. First off, the email goes straight to spam/junk folder and what i'm aware of, a real company would make a email server that goes to Inbox on submission and it is very unclear who the email is coming from. (screenshot attached: [https://media.discordapp.net/attachments/899643784143450142/971667475630546974/Screen_Shot_2022-05-05_at_4.57.37_pm.png](https://media.discordapp.net/attachments/899643784143450142/971667475630546974/Screen_Shot_2022-05-05_at_4.57.37_pm.png)) 
Ok, so let's get to the main point. When I click the link in the email, it comes up with "**INVALID TOKEN**" in red text too(screenshot attached: [https://media.discordapp.net/attachments/899643784143450142/971663266323529778/Screen_Shot_2022-05-05_at_4.42.38_pm.png](https://media.discordapp.net/attachments/899643784143450142/971663266323529778/Screen_Shot_2022-05-05_at_4.42.38_pm.png))

Can someone help me? I am using iCloud Mail and it ain't working. I am glad that I posted this to Github because it doesn't seem they tested it with iCloud Mail.

**Comment by Cynamicial** [comment] 2022-05-05 07:07
Zamn why does it fell like you're applying for a job XD?

**Comment by WWEMGamer2** [comment] 2022-05-05 07:24
> Zamn why does it fell like you're applying for a job XD?

"not"

**Comment by insertish** [comment] 2022-05-08 08:25
I believe the issue here is when someone creates an account, forgets about it and then tries to create an account again.
The problem is that it silently fails currently (https://github.com/insertish/rauth/issues/36), so the token it sends you is incorrect.

You can resend the link by going to https://app.revolt.chat/login/resend

I'm going to close this off since it's already tracked in the linked repository.

**Closed by insertish** 2022-05-08 08:25 UTC
