### ISSUE TITLE
feature request: inline date, time and countdown in messages

### ISSUE THREAD

**Issue by errhammr** [revoltchat/revolt#209] opened 2021-10-31 15:05 UTC
In the proprietary software product that Revolt may or may not be inspired by, there's a way to specify date and time values that are automagically converted to the local time zone of the user who is reading the message. This includes various flags for the desired format of date and/or time including a countdown. I'd love to have something like this in Revolt.

Basically if you type `<t:unixtimestamp>` it gets replaced by the localized date and time representation based on the locale of the user reading the message. `unixtimestamp` needs to be replaced with the integer that represents the desired Unix timestamp, of course.

[Further reading in the "official" docs](https://discord.com/developers/docs/reference#message-formatting-formats)

**Comment by insertish** [comment] 2021-10-31 16:05
Duplicate of #129

**Closed by insertish** 2021-10-31 16:05 UTC
Labels: duplicate
