### ISSUE TITLE
Revolt freezes after showing FileType error

### ISSUE THREAD

**Issue by ItzAmirreza** [revoltchat/revolt#315] opened 2022-02-28 12:08 UTC
Hey there,
As you may see in the video, revolt starts to freeze after I choose an unsupported type of picture for my profile.
https://streamable.com/hwonkg

**Comment by Rexogamer** [comment] 2022-03-10 18:43
Wrong repo - duplicate of revoltchat/revite#446.

**Closed by Rexogamer** 2022-03-10 18:43 UTC
