### ISSUE TITLE
bug: black rendering as white in icons

### ISSUE THREAD

**Issue by terminalmaid** [revoltchat/revolt#393] opened 2022-06-25 01:52 UTC
### What happened?

black is rendered as white in icons, which looks weird and hurts my eyes
example:
![Screenshot_20220625-024128_Brave](https://user-images.githubusercontent.com/50289495/175753834-152d8df8-5052-426c-aef1-5ce22e2f76f6.png)

**Comment by Rexogamer** [comment] 2022-11-05 16:49
Wrong repo, duplicate of revoltchat/revite#804 - if you're using Samsung Internet, try Jan's suggestion in that thread

**Closed by Rexogamer** 2022-11-05 16:49 UTC
Labels: bug
